'use client';

import Link from 'next/link';
import { useState, useTransition } from 'react';
import { toggleBusinessAction, toggleUserAction, updatePlanAction } from '@/app/(app)/admin/actions';
import { Badge, Button, Card, TextInput } from '@/components/ui/kit';
import type { Business, Plan, User } from '@/lib/types';

export default function AdminPlatformManager({ businesses, users, plans }: { businesses: Business[]; users: User[]; plans: Plan[] }) {
  const [pending, startTransition] = useTransition(); const [message, setMessage] = useState<string | null>(null);
  function run(action: () => Promise<void>, success: string) { setMessage(null); startTransition(async () => { try { await action(); setMessage(success); } catch (error) { setMessage(error instanceof Error ? error.message : 'Операция не выполнена'); } }); }
  return <div className="space-y-6">{message ? <p role="status" className="border border-line p-3 text-sm">{message}</p> : null}
    <details open className="ascii-details border border-line bg-surface p-4"><summary className="font-semibold uppercase">Бизнесы ({businesses.length})</summary><div className="mt-4 overflow-x-auto border-t border-line pt-3"><table className="w-full text-sm"><thead><tr className="text-left text-xs uppercase text-ink-soft"><th className="py-2">Бизнес</th><th>Тариф</th><th>Статус</th><th /></tr></thead><tbody>{businesses.map((business) => <tr key={business.id} className="border-t border-line"><td className="py-3"><Link className="font-medium text-brand hover:underline" href={`/admin/businesses/${business.id}`}>{business.name}</Link><p className="text-xs text-ink-soft">{business.city} · {business.slug}</p></td><td>{business.plan}</td><td><Badge tone={business.active === false ? 'danger' : 'success'}>{business.active === false ? 'Заблокирован' : 'Активен'}</Badge></td><td className="text-right"><Button variant="ghost" disabled={pending} onClick={() => run(() => toggleBusinessAction(business.id, business.active === false), business.active === false ? 'Бизнес активирован' : 'Бизнес заблокирован')}>{business.active === false ? 'Активировать' : 'Блокировать'}</Button></td></tr>)}</tbody></table></div></details>
    <details className="ascii-details border border-line bg-surface p-4"><summary className="font-semibold uppercase">Пользователи ({users.length})</summary><div className="mt-4 space-y-2 border-t border-line pt-3">{users.map((user) => <div key={user.id} className="flex flex-wrap items-center justify-between gap-2 border-b border-line py-2"><div><p className="text-sm text-ink">{user.name} · {user.login}</p><p className="text-xs text-ink-soft">{user.role} · {user.businessId ?? 'платформа'}</p></div><Button variant="ghost" disabled={pending} onClick={() => run(() => toggleUserAction(user.id, !user.active), user.active ? 'Пользователь отключён' : 'Пользователь включён')}>{user.active ? 'Отключить' : 'Включить'}</Button></div>)}</div></details>
    <details className="ascii-details border border-line bg-surface p-4"><summary className="font-semibold uppercase">Тарифы и лимиты</summary><div className="mt-4 grid gap-3 border-t border-line pt-3 lg:grid-cols-3">{plans.map((plan) => <PlanEditor key={plan.tier} plan={plan} pending={pending} run={run} />)}</div></details>
  </div>;
}

function PlanEditor({ plan, pending, run }: { plan: Plan; pending: boolean; run: (action: () => Promise<void>, success: string) => void }) {
  const [price, setPrice] = useState(String(plan.priceKzt)); const [customers, setCustomers] = useState(String(plan.limits.customers)); const [campaigns, setCampaigns] = useState(String(plan.limits.campaignsPerMonth)); const [staff, setStaff] = useState(String(plan.limits.staff)); const [branches, setBranches] = useState(String(plan.limits.branches)); const [promos, setPromos] = useState(String(plan.limits.activePromos));
  return <Card className="space-y-2 p-4"><h3 className="font-semibold uppercase text-brand">{plan.title}</h3><TextInput label="Цена, ₸/мес" value={price} onChange={(e) => setPrice(e.target.value.replace(/\D/g, ''))} /><div className="grid grid-cols-2 gap-2"><TextInput label="Клиенты" value={customers} onChange={(e) => setCustomers(e.target.value.replace(/\D/g, ''))} /><TextInput label="Рассылки" value={campaigns} onChange={(e) => setCampaigns(e.target.value.replace(/\D/g, ''))} /><TextInput label="Сотрудники" value={staff} onChange={(e) => setStaff(e.target.value.replace(/\D/g, ''))} /><TextInput label="Филиалы" value={branches} onChange={(e) => setBranches(e.target.value.replace(/\D/g, ''))} /><TextInput label="Акции" value={promos} onChange={(e) => setPromos(e.target.value.replace(/\D/g, ''))} /></div><Button disabled={pending} onClick={() => run(() => updatePlanAction(plan.tier, { priceKzt: Number(price), customers: Number(customers), campaignsPerMonth: Number(campaigns), staff: Number(staff), branches: Number(branches), activePromos: Number(promos) }), `Тариф «${plan.title}» обновлён`)}>Сохранить лимиты</Button></Card>;
}
