import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Badge, Card, Stat } from '@/components/ui/kit';
import { requireSession } from '@/lib/auth';
import { kzt, num } from '@/lib/format';
import { getRepo } from '@/lib/repo';

export default async function AdminBusinessPage({ params }: { params: Promise<{ id: string }> }) {
  await requireSession(['platform_admin']); const { id } = await params; const repo = await getRepo(); const business = await repo.getBusiness(id); if (!business) notFound();
  const [stats, staff, branches, subscription, users, promos] = await Promise.all([repo.getBusinessStats(id), repo.listStaff(id), repo.listBranches(id), repo.getSubscription(id), repo.listUsers(), repo.listPromos(id)]);
  return <div className="mx-auto max-w-5xl space-y-6"><Link href="/admin" className="text-sm text-ink-soft hover:text-brand">← В админ-панель</Link><header><p className="ascii-kicker">Бизнес платформы · {business.slug}</p><div className="mt-1 flex flex-wrap items-center gap-3"><h1 className="text-2xl uppercase tracking-[0.1em]">{business.name}</h1><Badge tone={business.active === false ? 'danger' : 'success'}>{business.active === false ? 'Заблокирован' : 'Активен'}</Badge></div><p className="mt-1 text-sm text-ink-soft">{business.city} · тариф {subscription.plan} · создан {new Date(business.createdAt).toLocaleDateString('ru-RU')}</p></header><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Stat label="Клиенты" value={num(stats.totalCustomers)} /><Stat label="Выручка 30 дней" value={kzt(stats.revenue)} /><Stat label="Сотрудники" value={num(staff.length)} /><Stat label="Акции" value={num(promos.length)} /></div><div className="grid gap-4 md:grid-cols-2"><Card><h2 className="font-semibold">Филиалы</h2><ul className="mt-3 space-y-2 text-sm">{branches.map((branch) => <li key={branch.id} className="border-b border-line pb-2"><p>{branch.title}</p><p className="text-xs text-ink-soft">{branch.address}</p></li>)}</ul></Card><Card><h2 className="font-semibold">Учётные записи</h2><ul className="mt-3 space-y-2 text-sm">{users.filter((user) => user.businessId === id).map((user) => <li key={user.id} className="flex justify-between border-b border-line pb-2"><span>{user.name}<small className="block text-ink-soft">{user.login}</small></span><Badge tone={user.active ? 'success' : 'muted'}>{user.role}</Badge></li>)}</ul></Card></div><Link href={`/b/${business.slug}`} className="inline-block border border-line px-4 py-2 text-sm text-ink hover:border-brand hover:text-brand">Открыть публичный сайт</Link></div>;
}
